### PR TITLE
Perf

### PR DESCRIPTION
**Pull request by Osveron**
I have implemented `next_line` method, because when I tried to change `next` in `Iterator` to return `&String`, I run into lifetime issue that I didn’t know how to resolve. I used `fxhash` here, I don’t know if it is the fastest hashing algorithm that I could use, but it is faster than the standard one.

### CODE REVIEW

**Comment by tmr232** [comment]
Thanks for the PR!
I am currently trying to decide whether I want this behind a flag or not.
@odedlaz any thoughts?

**Comment by Osveron** [comment]
I just received email and looked at the code, I should have used write_all instead of write, because write doesn't guarantee that the whole buffer gets written.

**Comment by tmr232** [comment]
@Osveron Do you think this can easily be implemented as optional?

**Comment by Osveron** [comment]
What exact part of the PR you want to be optional? You want to have two implementations of the same thing? The only differences  between previous version and mine is that my version won’t panic on non UTF-8 characters. If you want I can just add a command line switch to enable checking, and make it write some error instead of panicking.

**Comment by tmr232** [comment]
@Osveron Sorry for taking so long. And sorry for my request making no sense - I was a bit out-of-focus when I reviewed it, and for some reason thoughts that you're storing hashes instead of the strings themselves.
I'll try and get to reviewing and merging it ASAP.

**Comment by tmr232** [comment]
OK. Went over the code again and tested it. Looks good :+1: 
Thanks!

**Pull request merged**
